{
 "title": "Easee",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "charger",
    "label": "Charger",
    "query": {
     "query": "label_values(easee_charger_cloud_connection, charger)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_cloud_connection{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_firmware_version{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cable lock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_cable_locked{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_radio_access_technology{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total charged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "easee_charger_lifetime_energy{charger=\"$charger\"}",
     "legendFormat": "Current {{a}}"
    }
   ]
  },
  {
   "title": "Signal strength",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "easee_charger_signal_strength{charger=\"$charger\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "easee_charger_in_voltage{charger=\"$charger\"}",
     "legendFormat": "T{{ta}}-T{{tb}}"
    }
   ]
  },
  {
   "title": "Smart charging",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_smart_charging{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cable rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_cable_rating{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charged selected period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(easee_charger_session_energy{charger=\"$charger\"}[$__range]))",
     "legendFormat": "Current {{a}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "easee_charger_operation_mode{charger=\"$charger\"}",
     "legendFormat": "{{charger}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_operation_mode{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "easee_charger_total_power{charger=\"$charger\"}",
     "legendFormat": "power"
    }
   ]
  },
  {
   "title": "Charging power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "easee_charger_total_power{charger=\"$charger\"}",
     "legendFormat": "{{charger}}"
    }
   ]
  },
  {
   "title": "Charged this/last session",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "easee_charger_session_energy{charger=\"$charger\"}",
     "legendFormat": "Current {{a}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "easee_charger_total_phase_current{charger=\"$charger\"}",
     "legendFormat": "L{{l}}"
    }
   ]
  },
  {
   "title": "Output",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_output_phase{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_output_phase{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "easee_charger_output_phase{charger=\"$charger\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}