apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "easee-exporter.fullname" . }}
  labels:
    {{- include "easee-exporter.labels" . | nindent 4 }}
stringData:
  username: '{{ required "Easee username is required" .Values.username }}'
  password: '{{ required "Easee password is required" .Values.password }}'
